### ISSUE TITLE
Can't edit or delete an exisiting connection 

### ISSUE THREAD

**Issue by dwightkelly** [taskforcesh/issues#1]
Nothing happens when I try to edit (or delete) a connection I just created.

![screen shot 2018-11-19 at 3 10 21 pm](https://user-images.githubusercontent.com/160460/48732304-43bd2780-ec0d-11e8-9a2b-b73cbefd30ff.png)

**Comment by manast** [comment]
May I ask which browser are you using?

**Comment by dwightkelly** [comment]
Firefox 63.0.1 on Mac OS X

**Comment by manast** [comment]
ok, it could be verified on Firefox. As a workaround you could use Chrome until we release the fix.

**Comment by dwightkelly** [comment]
Verified Chrome worked

**Comment by manast** [comment]
Fixed.
