### ISSUE TITLE
Queue does not accept any metrics config

### ISSUE THREAD

**Issue by moein** [taskforcesh/issues#105]
As per documentation [here](https://docs.taskforce.sh/metrics/) we have to pass metrics config to the queue but based on typescript type there is no metrics key in the Queue options.
Additionally, to pass the metrics time there is an enum (MetricsTime) and instead of `Queue.utils.MetricsTime.TWO_WEEKS` we have to pass `MetricsTime.TWO_WEEKS`

This clearly indicates the doc is out of date. Can you please let me know if we still need to pass metrics config to the queue?

**Comment by manast** [comment]
Sorry for the late reply. I am a bit confused of the issue here. If you are using BullMQ then there is an enum ```MetricsTime```, if you are using Bull then you have to use ```Queue.utils.MetricsTime```. I do not see where the documentation is wrong here...

**Comment by victory-parloa** [comment]
@manast when you import using es6 modules, this does not work.

**Comment by manast** [comment]
@victory-parloa could you please provide some code snippet where enabling metrics would not work?

**Comment by manast** [comment]
If there is an issue with metrics, please report to the BullMQ repo, if the issue is solely with Taskforce.sh let me know and I will reopen.
