### ISSUE TITLE
Can not create connection

### ISSUE THREAD

**Issue by tropee-moein** [taskforcesh/issues#109]
We have no connection with subscription for 1 connection and we are getting the error no quota left
<img width="1122" alt="Screenshot 2022-10-26 at 13 26 19" src="https://user-images.githubusercontent.com/113172721/198014673-9435ec28-2a0c-4819-ae8d-b85daf53df2a.png">

**Comment by manast** [comment]
That looks strange, as I can see the quota shows 0 used of 1. Could you try to logout and login to see if there is some glitch with the quota value?

**Comment by tropee-moein** [comment]
@manast In the end once we got our connector running with team and name arguments it created the connection automatically in the dashboard.
