### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by main-kun** [taskforcesh/issues#11]
Hey guys. I'm using taskforce in kubernetes and loving it. But I have to build my own docker images and updates are kinda difficult. I just had a deployment go into a crashloop because there was a newer version of taskforce and it refused to start with the old version. I think an official docker image could help a lot with problems like that because I can just always fetch latest tag and avoid manually building images. It would also be useful for anyone running in docker of course.

**Comment by lxcid** [comment]
I love to have an official one.

I setup a simple one here

https://github.com/lxcid/taskforce-connector-docker/blob/master/Dockerfile

A few things I would like to be able to set through environment variables are connection name, although I can do that by overwrite the cmd command

**Comment by paullryan** [comment]
I've created a complete example at https://github.com/nomadreservations/taskforce-connector-docker that I use in production. 

The process for this to work for you would be to add the docker file then add either a quay.io or dockerhub autobuild that get's generated everytime you push to master. Then we can pull it in similar manner to the example in my Readme. I intend on maintaining this as close a possible until you have your own image. 

_FYI @manast_

**Comment by manast** [comment]
This has been supported for a while now: https://docs.taskforce.sh/getting-started/taskforce-connector#using-a-docker-container
