### ISSUE TITLE
Getting 500 error when going to dashboard

### ISSUE THREAD

**Issue by tropee-moein** [taskforcesh/issues#111]
An error appears at the bottom of the page
Error loading queue: "Http failure response for https://api.taskforce.sh/queues/xxxxxxx: 500 OK"

**Comment by manast** [comment]
Thanks for reporting. 
Could you pleas provide a bit more context? when exactly does this error appear?

**Comment by ManuuRoca** [comment]
Hey! Not sure if it's related but we had yesterday the same issue and we restarted the Redis service and it's back again, if this issue comes back might be something that's affecting several users then

Will post here if I have the same issue again, but for you to get it back on track might be a solution

**Comment by tropee-moein** [comment]
@manast The error appears when
 we open the dashboard
We see the green light on the connection but nothing loads and we see a 500 errors in network panel and bunch of 404
![Screenshot 2022-11-10 at 16 05 43](https://user-images.githubusercontent.com/113172721/201130310-c72e8701-550a-48f7-ba38-633872808c5a.png)

**Comment by tropee-moein** [comment]
Followed @ManuuRoca's suggestion and now everything is ok.
I guess at some point your side was down so the connector couldn't send the data.
Closing this one.
Cheers

**Comment by ManuuRoca** [comment]
Hey, as a super temp solution works but the `500` came back again at least over here, it worked for around 3 hours and we need to restart Redis again to make it work

Maybe we can re open this one to get some extra support

**Comment by manast** [comment]
@ManuuRoca it's quite strange that restarting the Redis service itself solves the issue. Are you also using the taskforce-connector or is it a direct Redis connection?

**Comment by ManuuRoca** [comment]
Hey! Sorry for the delay, got caught in other stuff

We are using a docker with the image of taskforce connector, i'll try to share some part of it
