### ISSUE TITLE
Can't go to monitor or alert tabs of a connection

### ISSUE THREAD

**Issue by tropee-moein** [taskforcesh/issues#113]
I'm trying to add a monitor and alert to the connection we have but it's not switching the tab and there are bunch of errors in the console.
![Screenshot 2022-11-28 at 13 42 08](https://user-images.githubusercontent.com/113172721/204280873-d53e2d26-37b4-410b-9732-afbe25121001.png)

**Comment by manast** [comment]
Thank you for reporting this. It seems like there is a regression that affects monitors and alerts on taskforce-connector based connections. We are working on a fix.

**Comment by manast** [comment]
This is solved now but for some reason, the CDN is taking an unusually long time to replace the old front-end files. As soon as the new code kicks in it should work.

**Comment by manast** [comment]
I have verified this is working now.
