### ISSUE TITLE
Why my sending queues are always empty? 

### ISSUE THREAD

**Issue by qazidop** [taskforcesh/issues#12]
I am running Redis on docker and trying to connect taskforce with taskforce-connector but I am unable to run it. I might be doing things in a wrong way and I need some help and guidance. 

When I am trying to connect taskforce with defaults this is what I am getting.
` $: taskforce -n "transcoder connection" -t TOKEN

Taskforce Connector v1.2.0 - (c) 2017-2018 Taskforce.sh Inc.

WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"7652161b-14ff-42f9-9909-4736e9696a09","data":{"res":"connections","cmd":"getConnection"}}
WebSocket: sending connection: transcoder connection
WebSocket:  retry in 5000ms
WebSocket: closed [Arguments] { '0': 1006 }
WebSocket: reconnecting...
WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"c4cbfeb4-00f2-4095-8e59-b5438db9646a","data":{"res":"connections","cmd":"getConnection"}}
WebSocket: sending connection: transcoder connection
WebSocket: received {"id":"4c10cf6e-9a6a-4f4b-8db8-79ee10831518","data":{"res":"connections","cmd":"getQueues"}}
WebSocket: sending queues  []
`
When I am trying to specify the host

`$ taskforce -n "transcoder connection" -t TOKEN -h redis://localhost:6379/2

Taskforce Connector v1.2.0 - (c) 2017-2018 Taskforce.sh Inc.

WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"85346e12-0409-4d09-8d23-8a73a5e6c417","data":{"res":"connections","cmd":"getConnection"}}
WebSocket: redis connection error  getaddrinfo ENOTFOUND redis://localhost:6379/2 redis://localhost:6379/2:6379
WebSocket: Reconnecting in 512 ms
WebSocket: redis connection error  getaddrinfo ENOTFOUND redis://localhost:6379/2 redis://localhost:6379/2:6379
WebSocket: Reconnecting in 1024 ms`

Can anyone please guide me through the steps ?

**Comment by lxcid** [comment]
Not sure if its similar issue but I couldn't get any listing as well, whether production or staging or local… I'm quite sure it was working about half a day ago…

**Comment by qazidop** [comment]
Could you tell me how did you setup for local environment? did you specify the localhost address?

**Comment by lxcid** [comment]
@qazidop I think the command should be

```sh
taskforce -n "transcoder connection" -t TOKEN -h localhost -p 6379 -d 2
```

**Comment by qazidop** [comment]
@lxcid Its working now what I was missing was database number. Did you update it to the latest version?

**Comment by lxcid** [comment]
nice! I'm on 1.2.0, did you have the "jobs" showing up?

I was connected but the jobs is not showing up

**Comment by qazidop** [comment]
Yes I can see them now but I don't know why but it's kept losing its connection in between 

`WebSocket: received {"id":"19074e7c-b626-49cd-892b-0cafd3c6b48e","data":{"res":"queues","cmd":"getJobCounts","queueName":"post-start-up"}}

WebSocket: received {"id":"c10d5949-f797-482d-aff0-94096f565870","data":{"res":"queues","cmd":"getCompleted","start":0,"end":100,"queueName":"post-start-up"}}
WebSocket: received {"id":"cd53967c-0c43-421c-924d-be5d6c8904a8","data":{"res":"queues","cmd":"getJobCounts","queueName":"post-start-up"}}
WebSocket: received {"id":"da2a9ea9-1ed3-422a-8cf2-42aa3baab14d","data":{"res":"queues","cmd":"getDelayed","start":0,"end":24,"queueName":"post-start-up"}}
WebSocket: received {"id":"034fbf81-ced6-4881-8ac3-239d231da144","data":{"res":"queues","cmd":"getDelayedCount","queueName":"post-start-up"}}
WebSocket: received {"id":"91dff8e5-b980-4915-beba-f341ae791743","data":{"res":"queues","cmd":"getWaiting","start":0,"end":24,"queueName":"post-start-up"}}
WebSocket: received {"id":"8e92dedc-5d66-42ff-8ff1-0b84abadcb6e","data":{"res":"queues","cmd":"getWaitingCount","queueName":"post-start-up"}}
WebSocket: received {"id":"70649b6d-e54c-4a1b-8e38-0afc93b4e389","data":{"res":"queues","cmd":"getFailed","start":0,"end":24,"queueName":"post-start-up"}}
WebSocket: received {"id":"bcf1ba1c-b859-4892-947d-d7c08d4ce8ae","data":{"res":"queues","cmd":"getFailedCount","queueName":"post-start-up"}}
WebSocket:  retry in 5000ms
WebSocket: closed [Arguments] { '0': 1006 }
WebSocket: reconnecting...
WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"ecffc331-1704-4354-a1aa-a4a4ee3b5f69","data":{"res":"connections","cmd":"getConnection"}}
WebSocket: sending connection: transcoder connection
WebSocket:  retry in 5000ms
WebSocket: closed [Arguments] { '0': 1006 }
`

**Comment by lxcid** [comment]
It keep disconnecting for me as well but my issue is I can't query my queue. I was able to do it about 12-15 hours ago…

```sh
Taskforce Connector v1.2.0 - (c) 2017-2018 Taskforce.sh Inc.
WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"1b906202-3c7c-4c5a-a109-5a30cdc5b49f","data":{"res":"connections","cmd":"getConnection"}}
WebSocket: sending connection: transcoder connection
WebSocket: received {"id":"8e09a0df-47d8-4f70-8f22-9a4f7a3b2fd5","data":{"res":"connections","cmd":"getQueues"}}
WebSocket: sending queues  [ { prefix: 'bull', name: 'jobs' } ]
WebSocket: received {"id":"b05c2c8a-a27e-4bc7-9add-c7d2fd31a8a0","data":{"res":"connections","cmd":"getQueues"}}
WebSocket: sending queues  [ { prefix: 'bull', name: 'jobs' } ]
WebSocket:  retry in 5000ms
WebSocket: closed [Arguments] { '0': 1006 }
WebSocket: reconnecting...
WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"85c6bc1d-f3ea-4f3f-b2a6-933a8d5030ef","data":{"res":"connections","cmd":"getConnection"}}
WebSocket: sending connection: transcoder connection
WebSocket: received {"id":"87424b75-337c-4ffc-9ac3-7bc830ea6d1d","data":{"res":"connections","cmd":"getQueues"}}
WebSocket: sending queues  [ { prefix: 'bull', name: 'jobs' } ]
```

**Comment by manast** [comment]
@lxcid ok, so according to the debug info there should be 1 queue:
```
WebSocket: sending queues  [ { prefix: 'bull', name: 'jobs' } ]
```
Is this correct?

does refreshing the connection in the UI not make the queue appear? maybe there is a javascript error that is breaking the page before the queues are popping up, could you check the javascript console please?

**Comment by manast** [comment]
@lxcid sorry for the delayed response. Would you mind to test again refreshing the connection to see if it works now?

**Comment by manast** [comment]
regarding the re-connections, it should be much more stable now, a heartbeat mechanism was missing in the websocket implementation.

**Comment by manast** [comment]
Gonna close this now since as far as I know it has been resolved.
