### ISSUE TITLE
[OnPremise] - Option to run Taskforce.sh in ECS / Docker?

### ISSUE THREAD

**Issue by sopeters** [taskforcesh/issues#120]
Looking into deploying on-premise and https://docs.taskforce.sh/on-premises only states an AMI deployment - is there an option for an ECS / Docker deployment?

**Comment by manast** [comment]
It is now available: https://docs.taskforce.sh/on-premises/docker
Let me know if it works as expected.

**Comment by manast** [comment]
Unfortunately, it is not possible to convert the license but if you have a longer contract in AWS please contact me via email and I can arrange something for you.
