### ISSUE TITLE
Unable to add additional teammates

### ISSUE THREAD

**Issue by MarcusHSmith** [taskforcesh/issues#128]
![Screenshot 2023-03-28 at 09 17 06](https://user-images.githubusercontent.com/5768890/228615742-0b794bd7-876f-4276-9b39-dd87a1afe16a.jpg)

![Screenshot 2023-03-29 at 10 10 46](https://user-images.githubusercontent.com/5768890/228615863-017c0266-2fb7-4738-afd3-07f009bf0c43.jpg)

Seeing an error when adding teammates. Any ideas?

**Comment by manast** [comment]
Is this on-premises? maybe you are not allowed to use @ on the name, as if that character is wrongly sluggified so then the validation fails. Could you rename the organization names so that @ becomes dash (-) instead?

**Comment by MarcusHSmith** [comment]
![Screenshot 2023-04-04 at 14 23 23](https://user-images.githubusercontent.com/5768890/229911792-322b2452-689d-431f-8e73-1e60282e65a8.jpg)

I'm an idiot. Was clicking "add team" when I should have been clicking "invitations +"
