### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by bharathnallamothu** [taskforcesh/issues#130]
@manast 

I am using BullMQ to create a Queue and have added a few jobs. I have also made respective workers process those jobs. However, I am encountering the following error: 'Converting circular structure to JSON. Starting at object with constructor 'ClientRequest', property 'socket' -> object with constructor 'Socket', property '_httpMessage' closes the circle.' Can you help me resolve this issue?

![image](https://user-images.githubusercontent.com/17136986/234490295-6338fa58-0edc-4a46-9b5a-b189365171c0.png)

**Comment by manast** [comment]
You are passing a complex object that has circular dependencies, and as data must be serialized to JSON you get this error. Make sure you only send as data the bare minimum that you need for your jobs.

**Comment by bharathnallamothu** [comment]
@manast  

here is the object i have sent 

is it still complex and big in size? FYI: i have Redis connected to Bullmq 

`{
  "chunk": [
    {
      "uniqId": "3105037c-594a-44a5-8a1a-3e72722bbba6",
      "userId": "64477e993ae48ff1180185cc",
      "body": "Dear User your OTP 1234 to login in our CTRL CAMPUS , Do not share this with any one - CTRLCA",
      "mobileNumbers": [
        "8464867607"
      ]
    },
    {
      "uniqId": "6de13245-3ab5-4d11-9882-7e333e41b734",
      "userId": "64477e9c3ae48ff1180185dd",
      "body": "Dear User your OTP 1234 to login in our CTRL CAMPUS , Do not share this with any one - CTRLCA",
      "mobileNumbers": [
        "8464867607"
      ]
    },
    {
      "uniqId": "aef23b83-612f-4c62-aeb1-8872b9ff7cba",
      "userId": "64477e9f3ae48ff1180185ee",
      "body": "Dear User your OTP 1234 to login in our CTRL CAMPUS , Do not share this with any one - CTRLCA",
      "mobileNumbers": [
        "8464867607"
      ]
    },
    {
      "uniqId": "e63df6e6-d6b3-4a93-ba87-f1860efd06ce",
      "userId": "64477ea33ae48ff1180185ff",
      "body": "Dear User your OTP 1234 to login in our CTRL CAMPUS , Do not share this with any one - CTRLCA",
      "mobileNumbers": [
        "8464867607"
      ]
    },
    {
      "uniqId": "ec1bbb94-85c5-4a5c-8a9c-4f5b0b57e281",
      "userId": "64477ea63ae48ff118018610",
      "body": "Dear User your OTP 1234 to login in our CTRL CAMPUS , Do not share this with any one - CTRLCA",
      "mobileNumbers": [
        "8464867607"
      ]
    },
    {
      "uniqId": "88999dd0-0756-4039-8ca0-6c82006871a6",
      "userId": "64477ea93ae48ff118018621",
      "body": "Dear User your OTP 1234 to login in our CTRL CAMPUS , Do not share this with any one - CTRLCA",
      "mobileNumbers": [
        "8464867607"
      ]
    },
    {
      "uniqId": "a33bb6d2-c17e-492e-b2e2-f5726d1cc17e",
      "userId": "64477eac3ae48ff118018632",
      "body": "Dear User your OTP 1234 to login in our CTRL CAMPUS , Do not share this with any one - CTRLCA",
      "mobileNumbers": [
        "8464867607"
      ]
    },
    {
      "uniqId": "818ec589-4efd-40e2-bbc5-c5ed0e0e6e95",
      "userId": "64477eb03ae48ff118018643",
      "body": "Dear User your OTP 1234 to login in our CTRL CAMPUS , Do not share this with any one - CTRLCA",
      "mobileNumbers": [
        "8464867607"
      ]
    },
    {
      "uniqId": "29947da1-e87c-4f8d-8a3a-efebb194cf3d",
      "userId": "64477eb33ae48ff118018654",
      "body": "Dear User your OTP 1234 to login in our CTRL CAMPUS , Do not share this with any one - CTRLCA",
      "mobileNumbers": [
        "8464867607"
      ]
    },
    {
      "uniqId": "a7b68b51-ca1b-46aa-841b-7e970f7f4ea1",
      "userId": "64477eb63ae48ff118018665",
      "body": "Dear User your OTP 1234 to login in our CTRL CAMPUS , Do not share this with any one - CTRLCA",
      "mobileNumbers": [
        "8464867607"
      ]
    }
  ]
}`

**Comment by manast** [comment]
I do not think that is the object that you really sent, as you can see in your error stack it is a different one that has stuff such as _httpMessage, etc.

**Comment by manast** [comment]
Can you see a data object in taskforce.sh? If you can, then the JSON error comes from your processor function where you are trying to serialize an object with JSON.stringify

**Comment by bharathnallamothu** [comment]
@manast 

here is the screen shot

![image](https://user-images.githubusercontent.com/17136986/234506803-4cb7c51c-94c3-4be9-9f56-a6b3e2745811.png)

**Comment by bharathnallamothu** [comment]
> Can you see a data object in taskforce.sh? If you can, then the JSON error comes from your processor function where you are trying to serialize an object with JSON.stringify

@manast  I thought the same. but if I hit "Retry all" from bull dashboard. then it's working. by default it's going to json circular error  ;(

**Comment by manast** [comment]
It looks like there is a bug in your processor code...

**Comment by manast** [comment]
The other place where a JSON stringification takes place in BullMQ is on the return value. Make sure that you are indeed returning a JSON stringifiable value from your processor.

**Comment by bharathnallamothu** [comment]
@manast Thank you so much for your help 

I was sending the whole circular response to redis bullmq.
