### ISSUE TITLE
Publish AMI With Upgraded Node Version

### ISSUE THREAD

**Issue by sjrumsby** [taskforcesh/issues#135]
Hello,

We run Taskforce on-prem, which from what I can tell comes pre-installed with Node `v16.15.1` via `nvm`. Node 16 goes end-of-life in a little under a month, on September 11th, 2023.

Do you have any plans to publish a new AMI that is running an upgraded version of Node?

Thanks!

**Comment by manast** [comment]
Yes, and also updated with the latest version of the dashboard.

**Comment by nikmash** [comment]
Hi @manast any idea what the timeline is for when that AMI will be available in the marketplace?

**Comment by manast** [comment]
A couple of weeks at the most.

**Comment by manast** [comment]
This was completed the 10th of September. New AMIs are available, version 1.2.0 using the latest AWS Linux 2023 as well as latest NodeJS 18.

**Comment by manast** [comment]
For reference, here is the link the new version: https://aws.amazon.com/marketplace/pp/prodview-bvdifzvjsoxsm?sr=0-1&ref_=beagle&applicationId=AWSMPContessa
