### ISSUE TITLE
Connection List - Cosmetic - Lines overlap when connection name wraps

### ISSUE THREAD

**Issue by gcox** [taskforcesh/issues#14]
Browser: Safari

In the connection list, if you have a connection name that wraps, the lines of text slightly overlap. See screenshot:

![Screenshot 2019-03-27 05 39 36](https://user-images.githubusercontent.com/251512/55066029-487a6800-5053-11e9-9267-1fa4cdd7f7d6.png)

**Comment by manast** [comment]
This has been fixed.
