### ISSUE TITLE
Unable to view prioritized jobs on taskforcesh dashboard

### ISSUE THREAD

**Issue by shashank90** [taskforcesh/issues#140]
Hi,

I am on the trial version of the `taskforcesh` dashboard. And am not able to find `prioritized` jobs tab

<img width="940" alt="Screenshot 2023-09-13 at 11 48 19 AM" src="https://github.com/taskforcesh/issues/assets/2920341/0755fef6-efa7-4f99-8134-8efa5683f665">

They don't seem to be included in the metrics section either.

<img width="909" alt="Screenshot 2023-09-13 at 11 47 45 AM" src="https://github.com/taskforcesh/issues/assets/2920341/4868217e-d45e-4603-977a-e51c2562925a">

Thanks
Shashank

**Comment by manast** [comment]
Prioritiotized jobs are now fully supported in the dashboard.
