### ISSUE TITLE
Account mgmt and subscription issues

### ISSUE THREAD

**Issue by ian-schu** [taskforcesh/issues#142]
Hi there, we could use some help getting our account out of (what appears to be) a bad state:
- The original engineer who configured our account left the company a while ago but they still appear to be the main admin on the account.
- We also had a credit card expire yesterday, and since providing new payment the UI still shows that we are on a trial. In this state **we are locked out** of the UI and can't see any of our queues or jobs.

We can discuss more details, but of course they should not go into a Github issue. Please reach out to me at ian@levelshealth.com, or you can use our team address eng@levelshealth.com. Thank you!

**Comment by manast** [comment]
Thanks for reaching out. I will contact you via email to resolve this issue.
