### ISSUE TITLE
Slack webhook - loosen input requirements

### ISSUE THREAD

**Issue by thesoftwarejedi** [taskforcesh/issues#145]
I'm attempting to use a slack compatible webhook endpoint but the input box for the webhook appears to have requirements around what is allowed there.  Specifically, I'm trying to use the [slack compatible webhook feature of discord](https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook).

The UI does not allow me to use this webhook although there is no technical reason not to.

**Comment by manast** [comment]
@thesoftwarejedi what error are you getting when you try to use discords endpoint?

**Comment by thesoftwarejedi** [comment]
“Invalid slack url” or such. The input doesn’t allow it. Can’t save.

**Comment by manast** [comment]
Could you paste an example of a url for discord?

**Comment by manast** [comment]
Closing due to lack of response.
