### ISSUE TITLE
Bullmq pro - max connections

### ISSUE THREAD

**Issue by lb-kamilk** [taskforcesh/issues#146]
Hey!
I am considering bullmq pro in order to use the groups feature. I see in the taskforce page that there is a 15 connections limit for enterprise license. I am using Kubernetes, and one pod has multiple queues, but one shared redis connection.

Is my understanding correct that I will be limited to using bullmq pro features to 15 pods in that case? Split across all my environments? Or is the limit only there if I want to use the UI?

If the limit is for 15 connections, does using the FlowProducer count as a connection? I have pods enqueueing messages separate from pods running the actual workers.

**Comment by manast** [comment]
@kozikkamil BullMQ Pro does not have any limit, you can use it in any number of projects as long as they belong to the same organization. On the other hand, the dashboard UI is limited depending on your subscription. A connection means one Redis host, you can have as many queues as you want in one host, and the connections can be shared to other team members.

**Comment by manast** [comment]
> If the limit is for 15 connections, does using the FlowProducer count as a connection? I have pods enqueueing messages separate from pods running the actual workers.

The limit is only for the UI, you can have as many FlowProducer's as you want.
