### ISSUE TITLE
Queued Jobs that are rate-limited due to their group, don't show up in Taskforce UI

### ISSUE THREAD

**Issue by ianwoodfill** [taskforcesh/issues#147]
With BullMQ Pro, we have groups configured with concurrency limits. When we queue more jobs that can be processed at once due to the concurrency limit, there is nowhere in the taskforce UI to see the waiting jobs. They don't show up under any of the job categories.

<img width="776" alt="CleanShot 2024-01-12 at 12 49 46@2x" src="https://github.com/taskforcesh/issues/assets/9495579/fbe72928-42c1-4a8a-9537-c6c01d7dd282">

This means we would have no way to tell that certain groups are being rate-limited.

**Comment by manast** [comment]
Normally you should see a "groups" tab when using BullMQ Pro, and the queue type should be BullMQ Pro, like this:
![image](https://github.com/taskforcesh/issues/assets/95200/8d321df5-d8fc-4283-8d32-d0786acd3c1b)
Is it possible that you are using the taskforce-connector and thus the queues are not detected as Pro? In that case you shoul use the Pro connector instead. You can find it on Account->BullMQ Pro

**Comment by ianwoodfill** [comment]
It is showing the queue as BullMQ Pro, yet the queued items in groups are not showing. It is working as expected, other than this (very useful feature by the way).
<img width="1501" alt="CleanShot 2024-01-15 at 09 19 44@2x" src="https://github.com/taskforcesh/issues/assets/9495579/a444b624-2e63-48ad-832d-d4cf2a2da667">

**Comment by manast** [comment]
I can see it is showing the groups tab/page:
![image](https://github.com/taskforcesh/issues/assets/95200/18885e53-3e5d-4cd9-8417-5bab0513126b)

**Comment by ianwoodfill** [comment]
Ah yes thank you, didn't realize it was another page.
