### ISSUE TITLE
Queues monitoring

### ISSUE THREAD

**Issue by nedyalkov** [taskforcesh/issues#15]
What I'm looking for is a way to monitor the health of my queues and workers. Not sure if this tool is meant for this, but as it is in the cloud and already has the metrics it seems like the right tool to integrate with my monitoring service (New Relic, Zabbix, etc.).

**Comment by nedyalkov** [comment]
I just noticed I'm not reading carefully that there is a suggestion for exposing monitoring metrics in the Bull repository: https://github.com/UpHabit/bull_exporter

**Comment by manast** [comment]
Alarms and metrics are in the roadmap for taskforce.

**Comment by manast** [comment]
Alerts and metrics have been implemented a while ago so closing this issue.
