### ISSUE TITLE
500 Error while trying to load queue metrics

### ISSUE THREAD

**Issue by taylorlapeyre** [taskforcesh/issues#150]
<img width="709" alt="Screenshot 2024-02-01 at 9 39 19 AM" src="https://github.com/taskforcesh/issues/assets/1610503/d0c15457-9f72-4a67-8be5-64b8da645fb3">
<img width="1257" alt="Screenshot 2024-02-01 at 9 40 15 AM" src="https://github.com/taskforcesh/issues/assets/1610503/13f453cd-07df-43c8-b940-79d149fbef0d">
<img width="448" alt="Screenshot 2024-02-01 at 9 40 21 AM" src="https://github.com/taskforcesh/issues/assets/1610503/93d385b1-4ad6-4bdb-b721-2b8bf6b00dc1">

**Comment by manast** [comment]
Seems to be some issue when Taskforce is trying to access the queues, most likely you are getting this error on your code as well.

**Comment by manast** [comment]
Normally this error is the consequence of some other previous error, maybe you can see something in the logs of the app using BullMQ.

**Comment by taylorlapeyre** [comment]
@manast thanks for the help! You're totally right — it was because we ran out of space in our redis instance. I'd really recommend a more helpful error message! It was pretty unclear that this was an error on our side and not Taskforce's.
