### ISSUE TITLE
Taskforce.sh with BullMQ Pro - Groups tab does not show any groups

### ISSUE THREAD

**Issue by wernermorgenstern** [taskforcesh/issues#153]
Hi, I am using the Trial Version of BullMQ right now (We are using the BullMQ Pro on a different account).

We are using the Groups Functionality of the Pro Version, with Concurrency set to 1 for some queues, but other queues, it is higher.

I see the jobs, but in the Groups tab, it shows as empty.

![image](https://github.com/taskforcesh/issues/assets/39772043/ec3c3466-e00f-456f-9671-573a81c30809)

**Comment by manast** [comment]
Are you sure there really are jobs in that queue? or that they really are in groups and not on the standard waiting status?

**Comment by wernermorgenstern** [comment]
Here is a list of the jobs:
![image](https://github.com/taskforcesh/issues/assets/39772043/8155ab88-51a3-4030-b0e3-08d3dc645b67)


And here is the Job Data:

![image](https://github.com/taskforcesh/issues/assets/39772043/6c0baab1-8f6f-4092-9dd3-e1b9f867d700)
As it shows, there is a group.id

**Comment by manast** [comment]
Ok, but could it be that the jobs are picked up very quickly so they do not have time to appear in any group? I see there are 91 active jobs currently, whats your maximum concurrency?

**Comment by wernermorgenstern** [comment]
They are picked up very quickly.  Group Concurrency is 1, and Worker Concurrency/Batch Concurrency is 10.

That could be.  What I could do, is pause the worker.  Let me try that

**Comment by wernermorgenstern** [comment]
Yes, you are correct.  I thought it would show also Completed Jobs.  Now I see it doesn't.
All good.  Thank you for your help on this.
