### ISSUE TITLE
UNABLE TO MAKE PAYMENT FOR IMIKIMI ZO

### ISSUE THREAD

**Issue by xlncmm** [taskforcesh/issues#158]
I AM UNABLE TO MAKE PAYMENT FOR THE SUBSCRIPTION OF IMIMIKIMI ZO , SINCE LAST 2 MONTH I AM TRYING TO RENEW THE SUBSCRIPTION BUT DID NOT SUCCEED.

**Comment by manast** [comment]
I need the email associated with this subscription, I cannot find it otherwise, please email me here with the information: manast@taskforce.sh

**Comment by xlncmm** [comment]
I already gave you the e-mail associated with subscription of IMIKIMI ZO.
even then I am again giving you the e-mail
***@***.*** ***@***.***> *
*MAN MOHAN DAGA*
