### ISSUE TITLE
UNABLE TO SUBSCRIBE FOR IMIKIMI ZO APP

### ISSUE THREAD

**Issue by xlncmm** [taskforcesh/issues#159]
I am trying to subscribe to IMIKIMI ZO  using my credit card (I'm from INDIA) but I am really struggling. I can add the card without problem but when I try to press "Update" the following error message pops up:
Error updating subscriptions: "Payment for this subscription requires additional user action before it can be completed successfully. Payment can be completed using the PaymentIntent associated with subscription.latest_invoice. Additional information is available here: https://stripe.com/docs/billing/subscriptions/overview#requires-action"

I don't have any kind of Adblock or anything that points towards a 3DSecure popup being blocked.

**Comment by manast** [comment]
Didn't you receive an email with further instructions?

**Comment by manast** [comment]
Could you please send me an email here: manast@taskforce.sh so I can look into it in more detail please.

**Comment by xlncmm** [comment]
> Didn't you receive an email with further instructions?

no I didn't receive any e-mail for further instructions

**Comment by manast** [comment]
Closing this issue as it is been handled via email.
