### ISSUE TITLE
Silly questions: TLS/SSL connection

### ISSUE THREAD

**Issue by dbronin** [taskforcesh/issues#16]
How can I use either the UI or the connector to connect to a redis instance that is secured with a certificate? Thank you.

**Comment by manast** [comment]
usually you run the connector in your VPC so it is not so critical to have the connection encrypted. But could you please contact me at manast@taskforce.sh with the details of your use case, since we have SSL on the roadmap for the connections.

**Comment by manast** [comment]
SSL is now supported in the connections.
