### ISSUE TITLE
ERROR:Unexpected queue type: bullmq-pro for queue XXX

### ISSUE THREAD

**Issue by vipin87** [taskforcesh/issues#161]
Right after launching taskforce connection, I am getting following error

```
ERROR:Unexpected queue type: bullmq-pro for queue XXX
```

Data from redis show this
Key: `bull:XXX:meta`
Value: `opts.maxLenEvents: 10000` and `version: bullmq-pro`

If I change value to `bullmq` inside redis then it works, otherwise if I use pro only then it doesn't.

**Comment by manast** [comment]
You should use the pro connector instead: 
<img width="338" alt="image" src="https://github.com/user-attachments/assets/060ef0a1-0935-4f9f-91a1-23f6b47bbb72">
