### ISSUE TITLE
Add support for "read-only" role in teams. 

### ISSUE THREAD

**Issue by manast** [taskforcesh/issues#168]
There should be a role that allows the team members to view the queues but not modify them in any way.

**Comment by ccorrado-moonpay** [comment]
Hello @manast thanks for creating the issue. Is there any update? Would be great to have this implemented so we can segregate access better while allowing access to the queues.

**Comment by manast** [comment]
Yeah, I actually wrote to you in the chat. The Guest role is supposed to fulfil this requirement, didn't it work for you?

**Comment by manast** [comment]
I think I know what happened here, it seems like you can only choose "Guest" when inviting a user but not after the user is in the team: 
![image](https://github.com/user-attachments/assets/7cb2fa2a-a5a2-4745-b1c9-f470c8ddfbf0)
I will fix this but in the meanwhile it should work to have guests users.

**Comment by ccorrado-moonpay** [comment]
Thanks @manast so it means that in order to move the current user already invited to the team we should remove their access and re-invite them?
I am about to test the Guest user these days. Thanks for the support and looking forward for the fix.

**Comment by manast** [comment]
This has now been fixed and verified that it works properly. All versions, Saas and OnPremises supports this feature now.
