### ISSUE TITLE
Help/Documentation Request

### ISSUE THREAD

**Issue by mikespangler** [taskforcesh/issues#169]
Hi @manast 

I have a queue with thousands of jobs from a certain concurrency group that have not been processed. The group concurrency limit is 25, and 25 are active at a time (expected). However, the waiting jobs do not appear in the waiting bucket, or anywhere on the dashboard. How can I see metrics or some representation of the waiting jobs?

<img width="355" alt="Screenshot 2024-10-02 at 2 39 28 PM" src="https://github.com/user-attachments/assets/8f479e8a-69a1-41a7-8e5c-d6918b66d891">

**Comment by manast** [comment]
You can only see groups in the official https://taskforce.sh dashboard, as they are stored in a different data structure that other third party front-ends do not understand.

**Comment by mikespangler** [comment]
Got it - thank you @manast!
