### ISSUE TITLE
Dashboard Guidance

### ISSUE THREAD

**Issue by mikespangler** [taskforcesh/issues#170]
Looking for some help understanding errors experienced while trying to connect the dashboard. 
I run `$ taskforce -n "mike local" -t <key>` and see a type error for each of my queues.

```
Taskforce Connector v1.32.0 - (c) 2017-2024 Taskforce.sh Inc.
WebSocket: opening connection to Taskforce.sh (wss://api.taskforce.sh)
WebSocket: opened connection to Taskforce.sh
WebSocket: received {"id":"b63a84c0-5032-4ac1-94ba-f8b80c0bf432","data":{"res":"connections","cmd":"getConnection"}}
Redis: connected to redis server
ERROR:Unexpected queue type: bullmq-pro for queue <queueName>
...
ERROR:Unexpected queue type: bullmq-pro for queuec<queueName>
WebSocket: sending connection: mike local 
WebSocket: data sent successfully in 14ms
```

on taskforce, my connection appears in the sidebar but no data is visible and I dont know what "Increase quota to show queues" refers to. 

thank you!

<img width="317" alt="Screenshot 2024-10-23 at 5 21 20 PM" src="https://github.com/user-attachments/assets/06de7be0-e7e5-46aa-af88-26f819ed7a40">

**Comment by mikespangler** [comment]
<img width="1638" alt="Screenshot 2024-10-25 at 3 36 03 PM" src="https://github.com/user-attachments/assets/30304be9-fa15-4afe-bdca-a2647df92f4b">

FWIW, I see the same behavior with the library implementation

**Comment by mikespangler** [comment]
Just checking in on this @manast. thank you!

**Comment by manast** [comment]
For some reason I have not got any notification until now for this issue, sorry for the delay answering. For seeing Pro queues you need to install the connector pro instead: @taskforcesh/connector-pro
However the error about the quota is strange, could you please send me the email associated to your account here: manast@taskforce.sh
