### ISSUE TITLE
BUG: Taskforce Queue management graph x-axis

### ISSUE THREAD

**Issue by rj-au** [taskforcesh/issues#174]
The x-axis used to be hard-coded to 5 days, now it's only the last hour.
We now can no longer see a reasonable amount of historical data.

![image](https://github.com/user-attachments/assets/0071a1a2-afdc-46c0-b01f-f5a2caa675e1)

Also, 1 hour `granularity` period is weird now:
![image](https://github.com/user-attachments/assets/98ffceeb-b398-4f4f-82c6-7b4eb47f4d15)

Related feature request to make x-axis configurable:
https://github.com/taskforcesh/issues/issues/173

**Comment by manast** [comment]
This is most likely because you have deleted the data in Redis. This view will show whatever data is in the metrics.

**Comment by rj-au** [comment]
OK - makes sense
