### ISSUE TITLE
QUESTION: Taskforce Queue management graph refresh

### ISSUE THREAD

**Issue by rj-au** [taskforcesh/issues#175]
Is there some sort of "Auto refresh" feature? I've been monitoring the Browser Network tab, but I'm not seeing any network traffic.

There is a "Refresh" button on the left side, this doesn't seem to update the graph, is it supposed to?
![image](https://github.com/user-attachments/assets/4d805e83-a66b-4d5c-b611-1b3473b58ba8)

**Comment by manast** [comment]
For the metrics there is no refresh, interestingly it seems like nobody has noticed this yet, we will add a refresh mechanism ASAP.

**Comment by rj-au** [comment]
Thanks - feel free to close this issue

**Comment by manast** [comment]
This has been deployed recently.
