### ISSUE TITLE
UX cuts off on the left when viewing jobs

### ISSUE THREAD

**Issue by slifty** [taskforcesh/issues#19]
When I navigate into a job list the left hand side which lists my queues gets cut off.  The only way to fix it is to click "Queues".

![ScreenFlow](https://user-images.githubusercontent.com/208884/58736021-59848400-83ca-11e9-94ed-bb665c57c72a.gif)

**Comment by manast** [comment]
Which browser is this?

**Comment by manast** [comment]
ok, firefox. :)

**Comment by slifty** [comment]
Ah apologies -- yes Firefox Quantum (67.0)

**Comment by manast** [comment]
Fixed!
