### ISSUE TITLE
The "longpress" event cannot be bound because Hammer.JS is not loaded and no custom loader has been specified.

### ISSUE THREAD

**Issue by dwightkelly** [taskforcesh/issues#2]
This warning is displayed in the console when I log into service.

The "longpress" event cannot be bound because Hammer.JS is not loaded and no custom loader has been specified.

**Comment by manast** [comment]
should be fixed now.

**Comment by badJaguar** [comment]
Not fixed yet. Sometimes it couldn't be load.
