### ISSUE TITLE
Clean out Completed Jobs

### ISSUE THREAD

**Issue by tbell511** [taskforcesh/issues#20]
Hi There!

First off I have to say that taskforce is great! My company will be purchasing a subscription as soon as the trial is out.  

I am wondering if there is a way to clear out completed jobs? I know there is a "remove on complete" option in bull, but I do want to retain access to completed jobs for X number of days, etc.  So is there a way to either automatically clear completed jobs or a way to do it manually? 

Thanks!

**Comment by manast** [comment]
Actually in the latest version of bull there is an option to specify the amount of jobs to retain, please check here: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd
```
 removeOnComplete: boolean | number; // If true, removes the job when it successfully
  // completes. A number specified the amount of jobs to keep. Default behavior is to keep the job in the completed set.
```

**Comment by tbell511** [comment]
This is perfect! Thanks!
