### ISSUE TITLE
Data Not Loaded

### ISSUE THREAD

**Issue by kariscomp** [taskforcesh/issues#21]
Hello team,

I am using Taskforce with a Compose Redis Deployment (Redis 4.0.14). The UI loads the jobs added(on the side menu) but does not load any metrics, jobs lists, scheduled jobs etc. However on Redis, I can see all the jobs created.

![Screen Shot 2019-07-12 at 3 33 10 PM](https://user-images.githubusercontent.com/4113576/61135940-898b7080-a4ba-11e9-8124-415c9d3908b6.png)
![Screen Shot 2019-07-12 at 3 33 26 PM](https://user-images.githubusercontent.com/4113576/61135942-898b7080-a4ba-11e9-8ad0-6fff262d6dcd.png)
![Screen Shot 2019-07-12 at 3 34 12 PM](https://user-images.githubusercontent.com/4113576/61135943-898b7080-a4ba-11e9-8e21-70efaf868e3e.png)

The UI was working before but stopped after activating a subscription.

**Comment by manast** [comment]
We have a known issue that we are working on a fix, and if it is the same one it can be workaround by refreshing the Connection (using the refresh icon), and then refreshing the page, let me know it that workaround works for you.

**Comment by kariscomp** [comment]
Thanks @manast. I tried the workaround with no luck, it still is blank. I will wait for the issue to be resolved.

**Comment by manast** [comment]
@kariscomp can you please contact me at manast@taskforce.sh to look into this more closely?

**Comment by kariscomp** [comment]
Closing since issue has been resolved. Thanks @manast
