### ISSUE TITLE
Dashboard gets stretched when selecting jobs, workers tabs

### ISSUE THREAD

**Issue by imagolive** [taskforcesh/issues#25]
This is using firefox.

![stretched page](https://user-images.githubusercontent.com/23182810/64315375-6ece0780-cfe4-11e9-88a9-ae4e2d7460fe.png)

**Comment by imagolive** [comment]
You have to scroll sideways to see stuff.

**Comment by manast** [comment]
yes, it is a duplicate of this one: https://github.com/taskforcesh/issues/issues/19 
Will give it high prio.

**Comment by manast** [comment]
Fixed!
