### ISSUE TITLE
expose job name/type

### ISSUE THREAD

**Issue by theoephraim** [taskforcesh/issues#26]
For my use case, I put related jobs into a single queue, but still have multiple different types of jobs within that queue. Given that bull supports this concept of a job type/name, I am very surprised to see this information not clearly exposed in the UI.

This should be very prominent, probably next to the ID in the table of jobs.

**Comment by santiagodoldan** [comment]
Are there any plans on doing this change? I have a similar situation and is really difficult to understand what each job means

**Comment by manast** [comment]
Fixed.
