### ISSUE TITLE
Removing team not working

### ISSUE THREAD

**Issue by yonidejene** [taskforcesh/issues#28]
Hello! 

Thank you for your work with Bull. It's one of our favorite libraries so we're happy to pay for Taskforce. 

I had one bug when I tried deleting a team. The warning modal was triggered and I was able to click the delete button but that it's stuck loading after that. 

I'm on Chrome Version 77.0.3865.90 (Official Build) (64-bit) and MacOS Mojave 10.14.5. 

Here's a screenshot of the response: 
![image](https://user-images.githubusercontent.com/19519903/65961105-95a22100-e45e-11e9-9235-75eba3aee575.png)

**Comment by olivierto** [comment]
Same setup, same result +1

**Comment by manast** [comment]
This has been fixed now.
