### ISSUE TITLE
Taskforce stopped working right after paying for it

### ISSUE THREAD

**Issue by bjesus** [taskforcesh/issues#30]
Hi,
Thank you for developing Bull.

Our trial with Taskforce finished today and so I wanted to subscribe. First, upon purchase, it told me that I'm paying the monthly fee of $15 for the period of Oct 31 - Oct 31. I don't really understand why I should pay a whole month just for one day. Or maybe it isn't the case?

Second, the dashboard stopped working. Everything shows 0 even though my queue has about 800,000 entries in it. It used to work fine before, except when we had a lot of data and that made the dashboard hang. Refreshing the connection and anything else that I try to do doesn't help and only shows error 500 in the network tab.

If the issue can't be fixed and Taskforce can't handle our queue, we would like to request a refund. I'd be happy to submit more information over email and not over public issues.

Thank you.

**Comment by manast** [comment]
please contact us at info@taskforce.sh and we will look into it ASAP.
