### ISSUE TITLE
Connect to a Redis Cluster?

### ISSUE THREAD

**Issue by xixxon** [taskforcesh/issues#32]
Hi.
Is there a way for me to connect taskforce to a redis cluster? Or the only way is to use 1 connection per node?
Thank you.

**Comment by manast** [comment]
Hello,

this is a very legit question. Currently we do not have support for cluster so the only alternative is to use one connection per node, but I will add this as a enhancement for next version.

**Comment by manast** [comment]
This should be fixed by now using version 1.9.0 and above.
