### ISSUE TITLE
Unable to add teammate to team 

### ISSUE THREAD

**Issue by timigod** [taskforcesh/issues#33]
I get an error message “Email does not match a valid member”

My initial suspicion is that it’s because the email’s domain name is “buycoins.africa”. I think the form validation may not support .africa domain names.

**Comment by manast** [comment]
This error is because the user does not have an account already, if you ask the user to first login so that the account is created and then you add him again it should work. 
We have as an enhancement the possibility to invite users when adding them to a team, but it is not ready yet.

**Comment by timigod** [comment]
@manast thanks!
