### ISSUE TITLE
Delete a queue

### ISSUE THREAD

**Issue by officert** [taskforcesh/issues#35]
I have some extra queues from when I was getting things setup. I've since changed the queue names, but in the UI I still see the old queues, even though they are empty.

It's not a huge issue, but it would clean things up if there was a way to delete old queues.

Thanks!

**Comment by manast** [comment]
This is probably because the old queues are not completely empty, there may be some left overs in redis. I will keep this issue as an enhancement so that we can complete remove a queue from the UI.

**Comment by officert** [comment]
Yea I noticed this with another queue, there seems to be a bunch of `null` jobs in the queue. If I look in the UI:

<img width="1130" alt="Screen Shot 2020-02-26 at 3 15 20 PM" src="https://user-images.githubusercontent.com/4620560/75383721-e6516500-58aa-11ea-807f-f33db8febdef.png">

It says 1796 jobs are in the queue, but the UI only shows 2 of them. I pulled them through the API and the rest of them are all `null`.

Here's page 2, you can see it just shows an empty list:

<img width="1129" alt="Screen Shot 2020-02-26 at 3 15 24 PM" src="https://user-images.githubusercontent.com/4620560/75383807-07b25100-58ab-11ea-99f8-9d76e6df657d.png">

^ This might be a separate issue, happy to log it in a new issue if that's helpful.

I tried deleting the jobs through the API and no luck either, they are just `null` so I can't call `job.remove()`.

**Comment by manast** [comment]
Ok, so for some reason jobs are getting nullified, this should be a bug report for https://github.com/optimalbits/bull 
but probably more info is needed, or if this could be reproduced somehow.

**Comment by manast** [comment]
Queues can now be deleted: https://docs.taskforce.sh/connections/queues
