### ISSUE TITLE
No way to update from monthly to yearly plan

### ISSUE THREAD

**Issue by lunchbag** [taskforcesh/issues#36]
Under Account, there doesn't seem to be a way to switch from a monthly to a yearly plan. I ended up canceling my monthly plan thinking that I could re-add a yearly one, but now I'm just stuck with no subscription.

<img width="1547" alt="Screen Shot 2020-04-06 at 4 30 09 PM" src="https://user-images.githubusercontent.com/1145302/78538644-e3d81880-7823-11ea-8e63-91e768199903.png">

**Comment by manast** [comment]
Ok. We will revisit this so that it is possible to upgrade to Yearly. As I understand, even though you cancel, you are still able to use the service until May 3rd right?

**Comment by lunchbag** [comment]
@manast Yup! Hoping this is fixed by May 3rd then :)

**Comment by lunchbag** [comment]
Looks like this was addressed; I was able to upgrade to a yearly plan. Thanks!
