### ISSUE TITLE
Cannot connect to DigitalOcean managed Redis instance

### ISSUE THREAD

**Issue by JVMartin** [taskforcesh/issues#39]
I have created a DigitalOcean manged Redis database:
![image](https://user-images.githubusercontent.com/4450814/83562600-b8457780-a4ce-11ea-89fa-d28b1b802c43.png)

(Note that the instance is open to *all* connections, from anywhere on the internet.)

I have set up the connection in taskforce.sh as so:
![image](https://user-images.githubusercontent.com/4450814/83562655-cc897480-a4ce-11ea-9767-ed63b5a84954.png)

The UI simply says "Unknown error":
![image](https://user-images.githubusercontent.com/4450814/83562679-d612dc80-a4ce-11ea-99f7-c427e698f8c1.png)

This is in my account registered as jacob@trendcapital.com

Please help me debug this issue. I can connect to the Redis instance from any other Redis GUI, and from my applications, no problem.

**Comment by manast** [comment]
I am looking into this and I could reproduce the issue with digital ocean provisioned instances.

**Comment by manast** [comment]
Ok, I found the issue. Digital Ocean instances require TLS, this is supported on taskforce dev version and I could verify it works as expected, this version will be released in the following days.

**Comment by JVMartin** [comment]
Awesome, looking forward to testing it out. Thanks!

**Comment by manast** [comment]
This has been released a while ago and verified with Digital Ocean so I will close it now, please comment if you find any issues:
![image](https://user-images.githubusercontent.com/95200/86456279-1c539980-bd22-11ea-88fe-4e9dc65f59ee.png)
