### ISSUE TITLE
Host/IP to whitelist for redis access

### ISSUE THREAD

**Issue by dwightkelly** [taskforcesh/issues#4]
What hostname(s) or IP(s) should we whitelist to allow access to our redis server?

**Comment by manast** [comment]
Currently the best approach for connecting to redis is using the connector: https://github.com/taskforcesh/taskforce-connector
Just run it on a given node that is already whitelisted and it will create a secure bridge to your taskforce account.

**Comment by manast** [comment]
This has been recently added: https://docs.taskforce.sh/getting-started/direct-redis-connection#securing-by-ip
