### ISSUE TITLE
Easy way to drop completed jobs?

### ISSUE THREAD

**Issue by msencenb** [taskforcesh/issues#40]
My redis instance memory is creeping up to beyond the server capacity. Is there a quick way to delete all completed Bull jobs so Redis can reclaim that memory through Taskforce?

There's that little trash button for individual jobs, but I've got 49k completed jobs to drop in this case. 

Any guidance would be appreciated :)

**Comment by manast** [comment]
Easiest is to use the ```removeOnComplete``` option when adding jobs to keep a maximum number of jobs, when you use this setting, the next time a job is completed your completed set will be trimmed to the chosen number: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd
