### ISSUE TITLE
An opened job is closed when the UI refetch data

### ISSUE THREAD

**Issue by jtassin** [taskforcesh/issues#41]
I have an instance with a lot of queues and jobs.
If I open a job using the UI to see the details.

The opened job will be closed as soon as an event is pushed from the server to the UI.

With lot of queue and jobs, it is impossible to open a job properly

**Comment by manast** [comment]
But the UI does not update itself unless you click on the refresh button, could you post a small video demonstrating the issue?

**Comment by jtassin** [comment]
> But the UI does not update itself unless you click on the refresh button, could you post a small video demonstrating the issue?

Thx for your answer @manast, strange I will post a video

**Comment by jtassin** [comment]
@manast you can download the video here : 

https://drive.google.com/file/d/1ET4HjxA_lWzIvnSez1Bd8jqSghVHut8G/view

my clicks are symbolised with red circles.

You will see that the job is closed automatically

**Comment by manast** [comment]
Ok. But it does not seem related to new jobs being processed since the list stays the same. Which browser and OS are you using?

**Comment by jtassin** [comment]
> Ok. But it does not seem related to new jobs being processed since the list stays the same. Which browser and OS are you using?

Chrome on macos

With the dev tools opened, I see a lot of xhr to the taskforce server and when a xhr is resolved my current opened job is closed.

Here is a screenshot of the xhrs

![taskforce](https://user-images.githubusercontent.com/1771191/85392041-47cccc00-b54b-11ea-949e-85fa7dbc7540.png)

**Comment by manast** [comment]
This is really weird. Does it happen with all the queues? Also, did this start happening recently?

**Comment by jtassin** [comment]
Yes all the queues.
It happens since at least a month, and this is a real pain once in production.

EDIT : in fact not all the queues only queues with a lot of traffic

**Comment by manast** [comment]
yes, In understand. What I find strange is that it has not been reported by other users and I cannot reproduce it myself. I wonder if it is something specific to your queue setup. If you try in another computer/browser do you get the same problem?

**Comment by jtassin** [comment]
Yes, we all have the same problem in my team

**Comment by jtassin** [comment]
I can create a redis instance with a script to create jobs to reproduce it if you want

**Comment by manast** [comment]
that would be quite useful

**Comment by manast** [comment]
you can send me private stuff here: manast@taskforce.sh

**Comment by jtassin** [comment]
> you can send me private stuff here: [manast@taskforce.sh](mailto:manast@taskforce.sh)

ok, I will provide it to you today

**Comment by jtassin** [comment]
The repo to reproduce is here : https://github.com/jtassin/taskforce-refresh-issue
I send to you by email the command to launch it

**Comment by jtassin** [comment]
All fixed, thx @manast
