### ISSUE TITLE
Unable to purchase subscription

### ISSUE THREAD

**Issue by cspags** [taskforcesh/issues#42]
Hello, I've added my credit card, but whenever I hit the Update button to purchase the subscription, it submits the form without actually completing the purchase.
![taskforce](https://user-images.githubusercontent.com/1913910/85933003-d3659600-b886-11ea-841c-e7dd8b805ba6.png)

**Comment by manast** [comment]
We just fixed an issue with the subscription update, would you kindly try again after a page refresh?

**Comment by cspags** [comment]
Thanks Manuel, I was able to make the purchase now. I really appreciate all of the work that you've put into Bull!
