### ISSUE TITLE
Show keyPrefix

### ISSUE THREAD

**Issue by dubiousdavid** [taskforcesh/issues#44]
We have multiple applications sharing a single Redis instance partitioned by key prefix. However, I have no way to differentiate them since the key prefix isn't shown. It would be great if you could render [keyPrefix].[queueName] if a keyPrefix exists wherever the queue name is shown. Thanks.

**Comment by dubiousdavid** [comment]
FYI, we are currently looking to use your product in production, but without some way to differentiate queues with the same name by their prefix that might not work for us.

**Comment by manast** [comment]
working on this feature today, I will let you know when it is ready.

**Comment by dubiousdavid** [comment]
Awesome! Thank you.

**Comment by manast** [comment]
The support for queue prefixes has now been released. If you use the taskforce-connector you will also need to upgrade to the latest version.
