### ISSUE TITLE
Multiple accounts support for panels with 1 paying account

### ISSUE THREAD

**Issue by bhoudu** [taskforcesh/issues#5]
Is it possible to give access to the panels to another user (using auth0 or any logging method) from the "main" paying account so having access to the panels does not equal having access to paying parameters as well?

**Comment by manast** [comment]
I am afraid that is not possible at the moment. But I will keep this issue as an enhancement proposal.

**Comment by jhashemi** [comment]
and this will be the reason I am not moving forward with this.

**Comment by shortcircuit3** [comment]
+1. I will ned this to share with my engineers

**Comment by manast** [comment]
The Team support has been ready for a while, although no invitation is sent yet via email, but it is coming soon, so I will close this issue has being resolved.

**Comment by cgtarmenta** [comment]
Hi! @manast 
I'm on a trial account, and my employer has invited me to join his team, I've received the invitation by email and clicked on the "check invitation" button
![image](https://github.com/user-attachments/assets/378e9d83-4851-4d86-825d-3b74a025d41d)

But that just takes me to the team's tab that still says I cannot add people to the team.

How should I join my employer team?

**Comment by manast** [comment]
You should see the team where you were invited and you can just accept to join or not.

**Comment by cgtarmenta** [comment]
Thanks for your answer @manast 

But that's the issue. There is no team appearing, and is just saying me I need to be subscribed to add people to teams...

**Comment by manast** [comment]
could you please send me a screenshot of the page here: manast@taskforce.sh
