### ISSUE TITLE
Remove connection

### ISSUE THREAD

**Issue by edurekatech** [taskforcesh/issues#52]
Hi,
We have 2 connection added via taskforce connector tool both are same just the name change is done. Now we want to remove 1 connection, How can we do that not getting option in Dashboard. Also we have stopped the taskforce connector. Now we stuck and can't use the UI as not able to remove the unwanted connection. Please help.

**Comment by manast** [comment]
Ok, normally when the connector is shutdown you can delete the connection, are you sure all the connectors are shut down?

**Comment by edurekatech** [comment]
Yes, All connectors are shut down.

**Comment by manast** [comment]
ok, let me look into it in detail.

**Comment by edurekatech** [comment]
Thanks, Got it. We checked again, It was due to the 1 of connectors is running. Now we are able to delete.
