### ISSUE TITLE
Can't provision

### ISSUE THREAD

**Issue by blocka** [taskforcesh/issues#55]
![image](https://user-images.githubusercontent.com/43194/99185641-33b38200-2719-11eb-97bd-a62622781047.png)
I get a broken modal. There are also JS errors in the console. I'm using chrome.

**Comment by manast** [comment]
This is quite strange, would you mind to paste the errors you get in the console? currently unable to reproduce this issue.

**Comment by blocka** [comment]
![image](https://user-images.githubusercontent.com/43194/99189798-14285380-2731-11eb-9992-822eee208ebb.png)
this is what I see when loading the page
![image](https://user-images.githubusercontent.com/43194/99189808-20141580-2731-11eb-9a61-ea58312b86d6.png)
this is what I see after opening the modal

**Comment by manast** [comment]
I did a small fix that would avoid that particular error, however the error should be impossible, could you refresh again and see what you get on the console now?

**Comment by blocka** [comment]
still doesn't work...but it works in incognito, so I guess one of my
extensions is screwing things up.

"however the error should be impossible"

the amount of times I've said that in my career :)

**Comment by manast** [comment]
Can you check in the network tab? maybe some call is being filtered out by some ad blocker or similar. The error comes from you account details being undefined.
