### ISSUE TITLE
Taskforce.sh as GitHub Marketplace app or Heroku addon

### ISSUE THREAD

**Issue by rvanmil** [taskforcesh/issues#56]
Would you consider offering the Taskforce.sh service through the GitHub Marketplace, or as a Heroku addon?
This will make it a lot easier for dev teams to pay for the service using their existing subscriptions and not go through budget approval bureaucracy etc.

**Comment by manast** [comment]
Thanks for the suggestion, I will look into it.

**Comment by ntellis** [comment]
I'll second this - would be excellent as a Heroku addon, especially if preconfigured to work with Heroku Redis. I could imagine it dynamically loading job queues from some common config, shared with the Heroku procfile. Not that the setup is particularly complicated to get the two to work together, but this would reduce adoption friction pretty significantly for Heroku users.

**Comment by manast** [comment]
The Heroku add-on is on the works actually, cannot give an ETA yet though.
