### ISSUE TITLE
Support usernames in Redis direct connection

### ISSUE THREAD

**Issue by jcuffe** [taskforcesh/issues#59]
Not sure if I'm missing out on some Redis culture, but my Heroku Redis has a `username` as well as a `password` (for authentication purposes, I think). 

Not being able to provide the username is preventing me from connecting.

**Comment by manast** [comment]
This is a new feature in Redis 6.0 and still not implemented, but I will prioritize it up.

**Comment by jcuffe** [comment]
Thank you! We will use the connector for now.

**Comment by manast** [comment]
username is supported now on connections, please let me know if it works for you.

**Comment by jcuffe** [comment]
Thank you for the fast update! Unfortunately, the connection to our Redis (Heroku hosted) is timing out. It looks like we are using a version older than 6.0, so the use of a username may be an additional layer added by Heroku. Here is what I was able to find using their tools:

```
$ heroku redis:info -a revel-x-production
=== redis-rectangular-76375 (REDIS_URL)
Plan:                   Premium 3
Status:                 available
Created:                2019-10-09 20:37 
Version:                4.0.14
Timeout:                300
Maxmemory:              noeviction
Maintenance:            not required
Maintenance window:     Thursdays 20:30 to Fridays 00:30 UTC
Persistence:            AOF
HA Status:              Available
Requires TLS:           No
Keyspace Notifications: Disabled
```

And here is a view of our config in the dashboard:
![image](https://user-images.githubusercontent.com/939223/110544175-2c591f80-80e0-11eb-8428-b210435f1e49.png)

The error given in dashboard is *Unknown error, tls disabled?*

**Comment by manast** [comment]
hmm, but is that the correct screenshot? I mean, the URL seems to go to an EC2 AWS instance not Heroku servers. Are you using Herokus official redis plugin or some other vendor?

**Comment by manast** [comment]
Also, you should make sure that your instance has opened access to the IP 18.193.189.120
(from https://docs.taskforce.sh/getting-started/direct-redis-connection)
![image](https://user-images.githubusercontent.com/95200/110594881-a25f9400-817d-11eb-8745-f39a47ac6585.png)

**Comment by jcuffe** [comment]
Thank you for the thread to pull! I will check incoming connection rules. Regarding Heroku vs AWS, I believe that Heroku relies on AWS for their infrastructure - our Postgres instance is also hosted on an AWS EC2 hostname.

**Comment by manast** [comment]
Closing this since AFAIK the feature is working, reopen if there are still issues.
