### ISSUE TITLE
Global overview of jobs

### ISSUE THREAD

**Issue by loris** [taskforcesh/issues#60]
It would be very helpful (at least for our usage) to have a global overview of all jobs, whatever queues they are in. For instance, a list of all the failed jobs globally. Right now we need to get inside hundreds/thousands of queues in order to check for this.

Is this something in your roadmap?

**Comment by manast** [comment]
There are plans to work with connections with many queue to facilitate navigation from the sidebar, however not like what you are suggesting. It will require to do a feasibility study in any case since that is functionality not available in Bull/BullMQ at the moment.

**Comment by loris** [comment]
I see, it would be great though. Most other background job system UIs (sidekiq, faktory, etc) have global dashboard where you can see aggregated metrics.
I was under the impression that the new QueueEvents classes using redis streams in bullmq would make it trivial for a taskforce.sh client to listen/store/aggregate/display those kind of metrics

**Comment by manast** [comment]
I will keep it open since it is not impossible that a feature like this could be implemented later on.
