### ISSUE TITLE
Subscriptions navigation is fudged

### ISSUE THREAD

**Issue by damusix** [taskforcesh/issues#61]
When I click between `Connection Token` , `Subscriptions` and `Teams` it doesn't route correctly. Sometimes I land on `Connection Token` and it never loads. Looks like js is throwing. I can click arouund and get to it but it's buggy.

![Screenshot from 2021-04-06 13-20-54](https://user-images.githubusercontent.com/4218587/113752447-fd33cf00-96da-11eb-8785-d2ea7bc004a8.png)

**Comment by manast** [comment]
thanks for reporting it, I will look into this right away.

**Comment by manast** [comment]
This issue has been resolved.
