### ISSUE TITLE
Retrying multiple failed jobs throws 500

### ISSUE THREAD

**Issue by damusix** [taskforcesh/issues#63]
![Screenshot from 2021-04-15 09-57-33](https://user-images.githubusercontent.com/4218587/114881464-0b67a680-9dd1-11eb-9adf-37d1c03d78d4.png)
![Screenshot from 2021-04-15 09-56-11](https://user-images.githubusercontent.com/4218587/114881467-0c003d00-9dd1-11eb-8fe3-7654e7c0d862.png)
![Screenshot from 2021-04-15 09-56-01](https://user-images.githubusercontent.com/4218587/114881469-0c003d00-9dd1-11eb-9794-c6d47a1d9775.png)

**Comment by manast** [comment]
thanks, will look into this ASAP.

**Comment by manast** [comment]
It should be resolved now.

**Comment by damusix** [comment]
Fixed! Thank you for the quick response.
