### ISSUE TITLE
Replace KEYS with SCAN

### ISSUE THREAD

**Issue by loris** [taskforcesh/issues#65]
Not sure if you are using the same code when connecting to your customers production database, but according to https://github.com/taskforcesh/taskforce-connector you are using the KEYS command ([client.keys("*:*:id");](https://github.com/taskforcesh/taskforce-connector/blob/master/lib/queues-cache.ts#L72)) to list all queues and it is said to be harmful: See warning section here https://redis.io/commands/KEYS
ioredis implements an easy to use scanStream method which should be used instead because it is non-blocking.
What do you think?

**Comment by manast** [comment]
Yes, however this call is done very seldom and it is actually really fast even with many keys. I will consider improving it using scan, just in case.
