### ISSUE TITLE
Provision is disabled

### ISSUE THREAD

**Issue by tarasyarema** [taskforcesh/issues#66]
Hi, today we created a new team and we found that we cant provision, as there's no plus button:

![image](https://user-images.githubusercontent.com/9470158/119203203-c6e7be80-ba92-11eb-8a15-1bce25cc191b.png)

It seems that it may be related to a region accessibility issue (?) In that case, we really do not care about the region it's deployed and would want to know how we could do so.

**Comment by manast** [comment]
Can you please contact me at "manast@taskforce.sh"?
