### ISSUE TITLE
Clean failed jobs

### ISSUE THREAD

**Issue by loris** [taskforcesh/issues#67]
Hello,

Currently, taskforce.sh has a "Clean waiting and delayed jobs" button (by the way, the icon could be made more relevant). It would be great to have buttons to clean jobs in any state (ie, "clean failed jobs").
In my experience of using bull with production business use-cases, we have little interest in "cleaning waiting jobs" (since they have not been handled yet, so we have little reason to remove them), but we regularly needs to "clean failed jobs" (for instance, they have been retried many times, and need to be manually removed)

Thanks

**Comment by manast** [comment]
So maybe what would be really useful is a way to remove jobs based on some filter, for example say you want to remove all failed jobs that have "attempts >  N" ? Because otherwise it could happen that when you click on the "remove all" button it would remove jobs that maybe have just failed in this moment and you will loose that information.

**Comment by loris** [comment]
@manast Sorry I missed your reply. Yes, being able to filter based on job attributes would be awesome.
In my opinion it could be an elegant solution to allows expanding the selection when you click on select all on any list of jobs in taskforce:

![image](https://user-images.githubusercontent.com/8362/126030648-fdeeaf42-f549-47c7-bb97-6c2148673a22.png)

On the screenshot above, it only select 25 jobs at once, you should add an option to expand to all matching jobs. This way, the user can list jobs of a given state, type in some filter, and then select all matching jobs and hit the "retry" or "remove" action.

This is what gmail do:
![image](https://user-images.githubusercontent.com/8362/126030675-88d63acb-06e9-494b-a04b-9d36c99b70a8.png)

**Comment by gitChristian** [comment]
Plus 1 on this

**Comment by manast** [comment]
This has been implemented for a while now. It is possible to delete all the jobs in the failed state (and other states as well independently).
