### ISSUE TITLE
Can we have more than 8 connections?

### ISSUE THREAD

**Issue by Pyvott** [taskforcesh/issues#69]
We just started evaluating Taskforce.sh, and noticed that we're limited to 8 connections:

<img width="289" alt="connections" src="https://user-images.githubusercontent.com/73312287/127521268-4764b9d5-c30b-4dc3-a174-d8d2104e0e86.png">

Is this just during the trial? Will we be able to move beyond 8 connections after we subscribe?

**Comment by manast** [comment]
You can have as many connections as you want: https://taskforce.sh/#pricing

**Comment by Pyvott** [comment]
Thanks for the quick response!

One more quick question: We want to use the taskforce connector as a library, as [documented here](https://github.com/taskforcesh/taskforce-connector#use-as-a-library); however, we have multiple API servers (behind a load balancer) connecting to the same Redis instance for the queue.

Should each API server use a unique connection name, or can they all use the same connection name since they're all connecting to the same Redis instance?

**Comment by manast** [comment]
They can all use the same connection name.

**Comment by Pyvott** [comment]
Thanks again!
