### ISSUE TITLE
Taskforce AWS Marketplace

### ISSUE THREAD

**Issue by kekami** [taskforcesh/issues#70]
Hello,

I'm trying to setup taskforce on-premises per the instructions here: https://docs.taskforce.sh/on-premises
However I am unable to locate taskforce in the AWS Marketplace, is this no longer available?

**Comment by manast** [comment]
Hello @kekami,

the application was just submitted and the AWS Marketplace is reviewing it. They told me it will be approved in 3 days if there are no impediments.

**Comment by kekami** [comment]
Oh! I see, then I'll await its release. Cheers!

**Comment by manast** [comment]
The service has finally been approved by AWS Marketplace. Let me know any issues you may encounter and if you need help.

https://aws.amazon.com/marketplace/pp/prodview-bvdifzvjsoxsm
