### ISSUE TITLE
`client` command unknown 

### ISSUE THREAD

**Issue by tarasyarema** [taskforcesh/issues#71]
Hi, we are getting the following errors after deleting a queue and restarting the service that recreates it:

```
ReplyError: ERR unknown command `client`, with args beginning with: `setname`, `bull:cGF5bWVudF90cmFja2luZw==`, 
```

**Comment by tarasyarema** [comment]
For context, the queue is recreated correctly, but when we load the Taskforce page for the queue it fails to loads.

**Comment by tarasyarema** [comment]
The request (from the console in Taskforce UI) is 

```
Request URL: https://api.taskforce.sh/queues/{some_queue_id}
```

And yields the following result:

<img width="473" alt="Screenshot 2021-09-30 at 11 23 22" src="https://user-images.githubusercontent.com/9470158/135425776-c3531e00-b39c-41dc-9665-8f14e5a47282.png">

**Comment by manast** [comment]
If you refresh the connection, does the queue appear in the list?

**Comment by tarasyarema** [comment]
Yes, it appears

**Comment by manast** [comment]
And when you select it from the list, what error do you get?

**Comment by tarasyarema** [comment]
The one I sent, it tries to load but timesout.

**Comment by manast** [comment]
Can you please provide a screenshot when this happens?

**Comment by tarasyarema** [comment]
<img width="1672" alt="Screenshot 2021-09-30 at 11 48 51" src="https://user-images.githubusercontent.com/9470158/135429938-d7cfbf3d-1fb9-43a0-a27a-dfd178c92051.png">

This is the error we get and we use GCP memory store for the Redis instance. The version is 4.0.

**Comment by tarasyarema** [comment]
For context, we had the same error in our other env (Sandbox one) yesterday but it stopped failing and it's back to normal now.

**Comment by manast** [comment]
I am not sure but I have a vague recollection that GCP has restricted some commands, maybe CLIENT SETNAME among them (since it is a command available since version 2 of redis). However I am not sure if this is related to this particular problem in any way. BTW, are you using the latest version of the taskforce connector? last version is 1.15.0.

**Comment by manast** [comment]
and something else, can you check the logs produced by the taskforce-connector to see if there are any errors there?

**Comment by tarasyarema** [comment]
Ok, we restarted the taskforce connector, as we were getting connection timeout errors there. For context we use version 1.13.0 of it but I would say its not related issue. Thanks for your time, closing the issue.
