### ISSUE TITLE
Unknown error, tls disabled?

### ISSUE THREAD

**Issue by AuroraDysis** [taskforcesh/issues#77]
I'm using a Redis instance provided by Redis Enterprise Cloud. I encountered the following error.
![image](https://user-images.githubusercontent.com/13709836/145312400-e4118bbf-da18-424e-8997-afc09939f045.png)

![image](https://user-images.githubusercontent.com/13709836/145312055-8136d87e-9cad-4ce5-9d22-86270afadbab.png)
I suspect it is due to a certificate problem. How can I provide a CA certificate?

**Comment by manast** [comment]
In theory, without using the "Require TLS client authentication" it should work by using the "redis ca fixed" certificate, however this does not seems to be supported by ioredis (https://github.com/luin/ioredis/issues/1076#issuecomment-989475892). It works well using redis-cli though.
So this will require support for uploading the certs to taskforce.sh. I will mark this as an enhancement.

**Comment by manast** [comment]
Also it is worth pointing out that other cloud providers TLS support is working well, it seems that the problem is limited to redis 6.0+ built-in SSL support.

**Comment by manast** [comment]
This issue has been resolved so now it is possible to use instances from Redis.com with TLS enabled, and if required two different profiles are available:

![image](https://user-images.githubusercontent.com/95200/151505200-4beb1189-f347-406b-8c95-473f789ed01b.png)
