### ISSUE TITLE
Subscription was not activated

### ISSUE THREAD

**Issue by IvanMMM** [taskforcesh/issues#8]
![image](https://user-images.githubusercontent.com/3692403/51119044-da2f5300-1822-11e9-815b-cb3237999973.png)
![image](https://user-images.githubusercontent.com/3692403/51119112-ffbc5c80-1822-11e9-912b-9ea4eeb70907.png)

**Comment by manast** [comment]
@IvanMMM we are working on a fix for this right now.

**Comment by IvanMMM** [comment]
Fixed, thank you for quick response

**Comment by IvanMMM** [comment]
But now it's another problem.
It shows available tasks for a second and then it disappears again

![image](https://user-images.githubusercontent.com/3692403/51138848-4e81ea80-1853-11e9-96eb-134917a77dc3.png)

**Comment by IvanMMM** [comment]
Fixed too. Thank you.
