### ISSUE TITLE
Does taskforce dashboard support jobs in "waiting-children" state in a Flow Producer setup?

### ISSUE THREAD

**Issue by shaunakv1** [taskforcesh/issues#80]
I can see my root level jobs in the waiting and active queues, but when I switch to the parent queue in the dashboard, I don't see an option to see the jobs in "waiting-childern" state. 

My children jobs can can take a while to run but parent job runs fairly quickly once all children are finished. I should also point out that actual parent jobs are running just fine, they are just never reported to the taskforce.sh dashboard.

**Comment by manast** [comment]
Yes you are right, since flows is a quite new feature there is no support for it in Taskforce.sh yet, but we will add support for it in the following months as its popularity is growing a lot lately.

**Comment by shaunakv1** [comment]
Thank you, that would be much appreciated! 

One another question, I also never see the completed parent jobs in the completed table on the dashboard. Would that be because I use `opts: { removeOnComplete: true }` in the Flow Producer? Or is that also because the Flow Producer isn't fully supported yet?

**Comment by manast** [comment]
With ```{ removeOnComplete: true }``` jobs will removed instead of stored in the completed set, but you could keep some amount for debugging for example with ```{ removeOnComplete: 10000 }```

**Comment by manast** [comment]
Waiting-children status is now supported, and therefore we support flows as well.
