### ISSUE TITLE
Internal Server Error when clicking "retry all failed" button

### ISSUE THREAD

**Issue by vhle-ms** [taskforcesh/issues#81]
This error show up in a toast after I click on the "retry all failed" button in the UI and clicking "Retry" in the confirmation modal:

`Error retrying jobs: "<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Internal Server Error</pre> </body> </html> "`

In the network tab, the request is: POST https://api.taskforce.sh/queues/{{queue_id}}/actions/retryall

Response payload: {"status":"failed"}

**Comment by manast** [comment]
What library are you using for the queues, Bull or BullMQ?

**Comment by vhle-ms** [comment]
We're using BullMQ

**Comment by manast** [comment]
And is it a direct connection or using the taskforce connector?

**Comment by vhle-ms** [comment]
Direct connection (over TLS) to Redis 6.2.6, hosted at RedisGreen

**Comment by manast** [comment]
Hmm, this is really strange. You wrote above that the Response payload was {"status": "failed"}, but that would be the request payload actually, i.e. what the POST sends to the server in the body, could you doublecheck what you are getting as a response from the server? it should be the actual error from trying to retry all the jobs.

**Comment by vhle-ms** [comment]
Just tried it again with two different queues, and it's working perfectly well now. I swear I was getting error toasts all day yesterday!

Sorry for the bother, and thank you for your help with this.

**Comment by manast** [comment]
Yes, I believe you 100%, it is a pity that we could not figure out the root of the issue. Do not hesitate to report if something similar happens in the future.
