### ISSUE TITLE
Re-subscription

### ISSUE THREAD

**Issue by RickyHolland** [taskforcesh/issues#82]
Hello,

We have re-added our payment card details on to our account so as to re-activate our subscription. It seems though that the re-activation has not automatically occurred, could you please assist?

For example, when browsing to the Teams option we are still instructed to subscribe.

![image](https://user-images.githubusercontent.com/22330292/155150072-6d5334d7-cb57-41bc-9270-775ebaa2068d.png)

We only require the standard monthly subscription and not BullMQ-Pro.

Username: ricky@merchstack.com

**Comment by manast** [comment]
@RickyHolland yes, we are in the middle of changing the subscriptions, that's why this happened to you. If you refresh and check again you should be able to see and subscribe to the connection packages.

**Comment by RickyHolland** [comment]
Poor timing on my part :).

Thanks, I've refreshed and have been able to resub.
