### ISSUE TITLE
Errors when loading dashboard

### ISSUE THREAD

**Issue by prescience-data** [taskforcesh/issues#83]
After signing up using Google account, I'm encountering toasts with error messages each time I load the dashboard.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/65471523/156071856-cef1a6f5-5568-4a15-813a-a0a94ac59c57.png">

```
Http failure response for https://api.taskforce.sh/organizations: 500 OK: ""<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Internal Server Error</pre>\n</body>\n</html>\n""

```

**Comment by manast** [comment]
If this error is stil there, can you send me an email here manast@taskforce.sh with your login email, I guess something broke in your account that is triggering a bug in the service, since I cannot reproduce this error.

**Comment by manast** [comment]
This issue was caused by the picture url in the given account being too long, we now support up to 2048 chars which is the maximum supported by Chrome anyway.
