### ISSUE TITLE
Metrics "Completed" and "Failed" charts both show counts of completed jobs

### ISSUE THREAD

**Issue by Jivings** [taskforcesh/issues#85]
Expected: 
   Bottom chart should show failed jobs.

Actual:
   Both charts show the completed counts.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/1462828/161380231-8c78f15c-84c6-440d-946a-4cc5aa00fc58.png">

**Comment by manast** [comment]
Thanks for reporting. This should have been fixed now.
