### ISSUE TITLE
When a job has a Timeout error I can no longer see the logs

### ISSUE THREAD

**Issue by Jivings** [taskforcesh/issues#86]
If a job fails because of a timeout, the errors section replaces the logs section so I cannot see the reason the logs of the job to find out why it took so long.

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/1462828/161464045-d4932cf6-f457-446e-b3d7-ae05ead8b7f8.png">

**Comment by manast** [comment]
Are you sure the job did produce lobs? I just checked some failed jobs and they all display their logs. Maybe your job died before it managed to output any log?

**Comment by Jivings** [comment]
Yes, you're right. It looks like some of my failed jobs are not logging. Though that is strange because they should at least log that they started, so it looks like these jobs never started...

**Comment by manast** [comment]
The call to "await job.log()" is the first thing done in the processor?

**Comment by Jivings** [comment]
Sorry, this was caused by me not reporting the error properly and the job not finishing and instead timing out. Thanks for your help, will close 👍
