### ISSUE TITLE
Ability to specify TTL per job instead of per queue

### ISSUE THREAD

**Issue by Jivings** [taskforcesh/issues#87]
It would be useful if I could provide a different TTL based on job name. 

Some of my jobs on a single queue are expected to take longer than others. They need to share a queue because they are rate-limited together.

**Comment by Jivings** [comment]
Any update on this? :) On Slack I think you said it was something you could get done?

**Comment by manast** [comment]
What means TTL in this context? should an active job die if it has lived more than a specific TTL?

**Comment by roggervalf** [comment]
hi @Jivings this feature was merged some time ago, but we were missing to add some docs, now you can reference by checking https://docs.bullmq.io/bullmq-pro/observables/cancelation

**Comment by Jivings** [comment]
That looks perfect, thanks @roggervalf!
