### ISSUE TITLE
cannot connect to heroku instance of redis

### ISSUE THREAD

**Issue by datagiliti** [taskforcesh/issues#95]
Not much more to say. It worked a few days ago and not it is not working. Nothing has changed on the heroku side that I can see. Same connection values etc but I notice the connection setup on the taskforce site does seem to have changed to provide a drop down to select reds.com profiles, which I do not need. might be a coincidence

**Comment by manast** [comment]
The dropdown for TLS profiles have been there for many months.
Can you please provide a bit more details, what error are you getting exactly, can you provide a screenshot of the error?

**Comment by manast** [comment]
Which version of Redis are you using? For Redis 6 it is a different connection scheme: https://devcenter.heroku.com/articles/heroku-redis#security-and-compliance
I can try to reproduce the issue if you provide me with the exact Redis version in Heroku.

**Comment by datagiliti** [comment]
Hi,
Thanks. I think you are correct. I have had to upgrade the level of redis on heroku and this then forces TLS where the free version does not.

This is the alert i can see.

	Queue
Connection	2022-06-13T12:20:33.998Z	Connection error (self signed certificate in certificate chain)	

Which is similar to issues i had myself.

The version is 6.2.3

Thanks

**Comment by datagiliti** [comment]
Hi,
A little more info. The error on the heroku side is
 Error accepting a client connection: (null)
Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by manast** [comment]
These are the settings I use for connecting to Heroku successfully, using Redis version 6.2.3
<img width="514" alt="image" src="https://user-images.githubusercontent.com/95200/174254656-e1b52a63-c3ff-49cd-bb06-5467645b44ed.png">

**Comment by datagiliti** [comment]
is that the free version or the paid version? It works for the free version not the paid version

**Comment by datagiliti** [comment]
for the paid version you need something like this:
`  client = new Redis({
    port: Number(redis_uri.port),
    host: redis_uri.hostname,
    password: redis_uri.auth.split(":")[1],
    db: 0,
    tls: {
      rejectUnauthorized: false,
      requestCert: true,
      agent: false,
    },
  });`

**Comment by manast** [comment]
I am using the paid version.

**Comment by manast** [comment]
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/95200/174267871-e4054175-4cf3-4f58-b829-0541ac9745e9.png">

**Comment by datagiliti** [comment]
i upgraded to heroku stack and wiped all config from taskforce, redeployed, reconfigured connection. Something in all that seems to have fixed the issue. Thanks for your patience and assistance

**Comment by samuelrondot** [comment]
I'm using the exact same issue on my Heroku logs : Error accepting a client connection: (null)
Using exact same parameters as you did on the screenshot above...

**Comment by samuelrondot** [comment]
Ok for some reason on Taskforce I just deleted my connection and created a new one with exact same informations and it now works.

**Comment by manast** [comment]
Closing as this seemed to be a transient issue with Heroku.
