### ISSUE TITLE
On premise dashboard not launching

### ISSUE THREAD

**Issue by Artsu** [taskforcesh/issues#98]
I recently launched Taskforce.sh on premise successfully for two of my environments. However with the exact same terraform configuration I ran into problems with third one. The configuration tool loaded successfully but when I try to access the dashboard on port 4200, it shows nothing. I ssh'd into the instance and when running `lsof -i -P -n | grep LISTEN`, it does not show port 4200 being listened at all (unlike on the working environments). 

When looking at `/home/ec2-user/.pm2/logs/Taskforcesh-error.log`, it seems to be printing the following constantly:
```
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

There doesn't seem to be anything running on that instance's 6379 but neither there is on the instances where the dashboard is working just fine. Image version I also confirmed to be the same. 

I've tried rebooting the instance and even deleting it and re-creating but to no avail. Any further things to check for what could be wrong?

**Comment by manast** [comment]
@Artsu thats really interesting. I made a new release today, and the new image uses a Redis instance. So it seems like 1) you are using the new image although AWS has not yet told me it has been approved and 2) the new image is not working correctly. I will look into this asap.

**Comment by manast** [comment]
The problem has been identified and a new version submitted to AWS, the new version is 1.1.1, you should get an email as soon as it is available. Also if you are upgrading older instances, here is a guide: 
https://docs.taskforce.sh/on-premises/upgrading

Also it may be of interest this new doc: 
https://docs.taskforce.sh/on-premises/monitors

**Comment by Artsu** [comment]
@manast It's working now, thanks a lot for quick response! I thought I was going crazy after running two setups with the same terraform config almost back to back and the second one wasn't working 😄

**Comment by manast** [comment]
Just one thing, is it possible to fix in the terraform config the AMI version for the On Premises instance? Just thinking that in the future there may come breaking changes and you could end with a similar problem if it just takes the latest version automatically.
